
// Objective-C API for talking to the following Go packages
//
//	github.com/Frtertaer/milkyvpn/milky-core/pkg/kal2mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mirage_FRAMEWORK_H__
#define __Mirage_FRAMEWORK_H__

#include "Kal2mobile.objc.h"
#include "Universe.objc.h"

#endif
