/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/Frtertaer/milkyvpn/milky-core/cmd/kal2native */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 7 "main.go"


#include <jni.h>
#include <stdlib.h>
#include <android/log.h>

static const char* jniGetStr(JNIEnv* env, jstring s) {
    if (s == NULL) return NULL;
    return (*env)->GetStringUTFChars(env, s, NULL);
}
static void jniRelStr(JNIEnv* env, jstring s, const char* p) {
    if (s != NULL && p != NULL) (*env)->ReleaseStringUTFChars(env, s, p);
}
static jstring jniNewStr(JNIEnv* env, const char* p) {
    return (*env)->NewStringUTF(env, p == NULL ? "" : p);
}
static void jniLog(const char* tag, const char* msg) {
    __android_log_write(ANDROID_LOG_INFO, tag, msg);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern jint Java_homes_milky_vpn_bridge_NativeBridge_nativeStart(JNIEnv* env, jclass _, jstring cfg);
extern void Java_homes_milky_vpn_bridge_NativeBridge_nativeStop(JNIEnv* env, jclass cls);
extern jboolean Java_homes_milky_vpn_bridge_NativeBridge_nativeAlive(JNIEnv* env, jclass cls);
extern jstring Java_homes_milky_vpn_bridge_NativeBridge_nativeLastError(JNIEnv* env, jclass cls);

#ifdef __cplusplus
}
#endif
