// Objective-C API for talking to github.com/Frtertaer/milkyvpn/milky-core/pkg/kal2mobile Go package.
//   gobind -lang=objc github.com/Frtertaer/milkyvpn/milky-core/pkg/kal2mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Kal2mobile_H__
#define __Kal2mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol Kal2mobileLogSink;
@class Kal2mobileLogSink;

@protocol Kal2mobileLogSink <NSObject>
- (void)log:(NSString* _Nullable)msg;
@end

/**
 * Alive reports whether a session is currently connected.
 */
FOUNDATION_EXPORT BOOL Kal2mobileAlive(void);

/**
 * SetLogSink installs a LogSink for kal2 log lines (mobile entry point).
 */
FOUNDATION_EXPORT void Kal2mobileSetLogSink(id<Kal2mobileLogSink> _Nullable s);

// skipped function SetLogger with unsupported parameter or return types


/**
 * Start connects with the JSON config, enables the reconnect watchdog, and
returns the local SOCKS5 listen port (e.g. 10808).
 */
FOUNDATION_EXPORT BOOL Kal2mobileStart(NSString* _Nullable configJSON, long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * Stop tears the session down (idempotent).
 */
FOUNDATION_EXPORT void Kal2mobileStop(void);

@class Kal2mobileLogSink;

/**
 * LogSink receives 'kal2: ...' log lines. gomobile cannot bind SetLogger
directly (function-typed parameters are unsupported), so ObjC/Swift and
Java/Kotlin callers implement this interface instead.
 */
@interface Kal2mobileLogSink : NSObject <goSeqRefInterface, Kal2mobileLogSink> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)log:(NSString* _Nullable)msg;
@end

#endif
